config/routes.rb
Rails.application.routes.draw do
  resources :members
  get 'home/about'
  get "members/new"
  root "members#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

    <%= link_to "Members", root_path, class:"navbar-brand text-primary" %>
    
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <li class="nav-item">
        <%= link_to "Create a member", members_new_path, class:"nav-link" %>
      </li>

      <li>
        <%= link_to "About", home_about_path, class:"nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1> This is the About page</h1>

app/views/home/index.html.erb
<h1>Hello world!</h1>
<p>This is my first Ruby app</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>My Crud</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>




<%
=begin%>
 <!DOCTYPE html>
<html>
  <head>
    <title>Mycrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html> 
<%
=end%>

app/views/members/_form.html.erb
<div class="jumbotron">
  <%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block", class:"text-primary" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block", class:"text-primary" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block", class:"text-primary" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block", class:"text-primary" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block", class:"text-primary" %>
    <%= form.text_field :twitter,class:"form-control" %>
  </div>

  <br/><br/>

  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>" class="jumbotron">

  <p class="lead">
    <strong class="font-weight-bold">First name:</strong>
    <%= member.first_name %>
  </p>
 
  <p class="lead">
    <strong class="font-weight-bold">Last name:</strong>
    <%= member.last_name %>
  </p>

  <p class="lead">
    <strong class="font-weight-bold">Email:</strong>
    <%= member.email %>
  </p>

  <p class="lead">
    <strong class="font-weight-bold">Phone:</strong>
    <%= member.phone %>
  </p>

  <p class="lead">
    <strong class="font-weight-bold">Twitter:</strong>
    <%= member.twitter %>
  </p>

</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member, class:"btn btn-success" %>
  <%= link_to "Back to members", members_path, class:"btn btn-secondary" %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Members</h1>

<table class="table table-hover table-striped">
  <thead class="thead-dark">
    <tr>
      
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th> 
      <th scope="col">Twitter</th>
      <th scope="col" class="text-center">#</th>
      <th scope="col" class="text-center">#</th>
      <th scope="col" class="text-center">#</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member|%>
      <tr>
        <td><%= member.first_name%></td>
        <td><%= member.last_name%></td>
        <td><%= member.email%></td>
        <td><%= member.phone%></td>
        <td><%= member.twitter%></td>
        <td><%= link_to "Show", member, class:"btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_member_path(member), class:"btn btn-warning" %></td>
        <td><%= button_to "Delete", member, method: :delete, data: { confirm: "Are you sure ?" }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to "Add a member", new_member_path, class:"btn btn-primary" %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path, class:"btn btn-secondary"%>
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member), class:"btn btn-success" %>
  <%= link_to "Back to members", members_path, class:"btn btn-secondary"%>
  <br/><br/>
  <%= button_to "Delete member", @member, method: :delete, class:"btn btn-danger"%>
</div>